/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#F7F5F0',
        bg2: '#EDE9E2',
        surface: '#FFFFFF',
        amber: '#CF8008',
        amber2: '#F0A020',
        cream: '#1A1714',
        muted: '#8A7E6E',
        dim: '#E4DFD6',
        danger: '#DC2626',
        safe: '#16A34A',
      },
      fontFamily: {
        display: ['Cormorant Garamond', 'serif'],
        ui: ['DM Sans', 'sans-serif'],
      },
      keyframes: {
        fadeUp: { '0%': { opacity: 0, transform: 'translateY(20px)' }, '100%': { opacity: 1, transform: 'translateY(0)' } },
        fadeIn: { '0%': { opacity: 0 }, '100%': { opacity: 1 } },
        scaleIn: { '0%': { opacity: 0, transform: 'scale(0.88)' }, '100%': { opacity: 1, transform: 'scale(1)' } },
        pulse: { '0%,100%': { opacity: 1, transform: 'scale(1)' }, '50%': { opacity: 0.6, transform: 'scale(0.95)' } },
        glow: { '0%,100%': { boxShadow: '0 0 12px rgba(207,128,8,0.20)' }, '50%': { boxShadow: '0 0 28px rgba(207,128,8,0.45), 0 0 48px rgba(207,128,8,0.12)' } },
        laser: { '0%': { top: '0%' }, '100%': { top: '100%' } },
        ping: { '0%': { transform: 'scale(1)', opacity: 1 }, '100%': { transform: 'scale(2.4)', opacity: 0 } },
        letterIn: { '0%': { opacity: 0, transform: 'translateY(32px) rotateX(-40deg)' }, '100%': { opacity: 1, transform: 'translateY(0) rotateX(0)' } },
        assemble: { '0%': { transform: 'translateY(-30px) rotate(-15deg)', opacity: 0 }, '60%': { transform: 'translateY(4px) rotate(2deg)', opacity: 1 }, '100%': { transform: 'translateY(0) rotate(0)', opacity: 1 } },
        dotPulse: { '0%,100%': { transform: 'scale(1)', opacity: 0.7 }, '50%': { transform: 'scale(1.5)', opacity: 1 } },
        checkIn: { '0%': { transform: 'scale(0) rotate(-30deg)', opacity: 0 }, '100%': { transform: 'scale(1) rotate(0)', opacity: 1 } },
        cardFan: { '0%': { opacity: 0, transform: 'translateX(40px)' }, '100%': { opacity: 1, transform: 'translateX(0)' } },
        pinDrop: { '0%': { transform: 'translateY(-20px) scale(0)', opacity: 0 }, '70%': { transform: 'translateY(4px) scale(1.15)' }, '100%': { transform: 'translateY(0) scale(1)', opacity: 1 } },
        scanline: { '0%,100%': { opacity: 0.04 }, '50%': { opacity: 0.09 } },
      },
      animation: {
        fadeUp: 'fadeUp 0.5s ease forwards',
        fadeIn: 'fadeIn 0.3s ease forwards',
        scaleIn: 'scaleIn 0.5s ease forwards',
        pulse: 'pulse 2s ease infinite',
        glow: 'glow 2s ease-in-out infinite',
        laser: 'laser 1.8s ease-in-out infinite',
        ping: 'ping 0.8s ease-out infinite',
        letterIn: 'letterIn 0.5s cubic-bezier(.34,1.56,.64,1) forwards',
        assemble: 'assemble 0.7s cubic-bezier(.34,1.56,.64,1) forwards',
        dotPulse: 'dotPulse 1s ease infinite',
        checkIn: 'checkIn 0.4s cubic-bezier(.34,1.56,.64,1) forwards',
        cardFan: 'cardFan 0.4s cubic-bezier(.34,1.56,.64,1) forwards',
        pinDrop: 'pinDrop 0.5s cubic-bezier(.34,1.56,.64,1) forwards',
        scanline: 'scanline 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
